services:
   road.api:
      image: roadapi
      container_name: roadapi
      ports:
         - 8080:8080
   road.seq:
      image: datalust/seq:latest
      container_name: roadseq
      environment:
         - ACCEPT_EULA=Y
         - SEQ_FIRSTRUN_ADMINUSERNAME=admin
         - SEQ_FIRSTRUN_ADMINPASSWORD=password
      ports:
         - 5341:5341
         - 8081:80
